name: 'Send message'
description: 'Send message use actions'
author: 'James Yang'
inputs:
  server:
    description: 'Server name.'
    default: 'email'
    required: true
  smtp:
    description: 'Email SMTP server domain.'
    default: 'smtp.qq.com'
  smtp-auth:
    description: 'SMTP identity authentication.'
    default: true
  port:
    description: ''
    default: '465'
  ssl:
    description: ''
    default: 'true'
  email:
    description: 'Email name.'
  password:
    description: 'Email password.'
  serverchan-key:
    description: 'ServerChan Turbo key.'
  title:
    description: 'Message title.'
    required: true
  message:
    description: 'Send message.'
    required: true
outputs:
  send-time:
    description: 'Send message time.'
runs:
  using: 'node12'
  main: 'lib/index.js'
