name: setup-mauve
on: [push]
jobs:
  set-mauve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://llxlr/setup-mauve:progressiveMauve
      - run: progressiveMauve --version
      - uses: docker://llxlr/setup-mauve:mauveAligner
      - run: mauveAligner --version
